baseURL: "https://farason.co/public/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Farason Corporation"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Farason Corporation"
  description: "We specialize in the design and build of highly reliable and productive flexible automation and robotic systems designed for rigorous 24/7 operation."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "855 Fox Chase Rd. Coatesville, PA 19320
"

  contact:
    - "info@farason.com"
    - ""

  copyright: "Â© 2023 Farason Corporation, All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Schedule a visit"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#"
      weight: 1

    - name: "How we work"
      url: "/#hero"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
